### ISSUE TITLE
Error with v1.19.70

### ISSUE THREAD

**Issue by oscarmlage** [TheRemote/Legendary-Minecraft-Purpur-Geyser#7] opened 2023-03-15 19:47 UTC
It seems that there is an error trying to play with 1.19.70 version:

"Server does not support Java Edition 1.19.4, required for Geyser to connect. Server has to be updated or install ViaVersion plugin"
"Disconnect message: Outdated server! I'm still on 1.19.3"

May I help in any way to fix this issue? (thanks in advance)

**Comment by TheRemote** [comment] 2023-03-15 19:57
Yes, 1.19.4 was released but Purpur Minecraft 1.19.4 was not released yet.  This will happen every Minecraft update.

This update will be available when the Purpur team releases it at page: https://purpurmc.org/downloads

The only way around this is to connect with an older Bedrock client (not easy to do since the Microsoft Store automatically updates it).

It typically only takes a day or two for the team to finish up the patch and then the newer Bedrock clients will be able to connect!

To be clear the problem is your Bedrock clients are updating themselves to what is essentially the Bedrock version of Java 1.19.4.  It has newer features in it that aren't ready for the server yet.  The Purpur Minecraft team needs time to incorporate the new patch.

You might be able to use the ViaVersion plugin to bypass this possibly: https://www.spigotmc.org/resources/viaversion.19254/

Hopefully that helps!

**Comment by TheRemote** [comment] 2023-03-15 21:24
Actually I have something else for you to try.

Can you try closing the container and then doing a:

`docker pull 05jchambers/legendary-minecraft-purpur-geyser:latest`

And try running again?

**Comment by TheRemote** [comment] 2023-03-15 21:52
This has been fixed in ViaVersion as per https://github.com/TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate/issues/18

Thanks!

**Closed as completed by TheRemote** 2023-03-15 21:52 UTC
